#!/usr/bin/env python3
"""The images a link preview needs, as REAL FILES, plus the meta that names them.

Sharing the app used to produce a card in iMessage with the icon on it and
the app's own colour behind it, and it stopped. The page had no Open Graph
metadata at all - no og:image, no og:title, no og:description - so every
preview was working from whatever it could scrape, and the one thing it
could have scraped is `apple-touch-icon`, which is a base64 `data:` URI.

That is the same lesson `launch/` already cost a session: iOS wants a
FETCHABLE PATH. A crawler asks for the page and then asks for the image;
it does not decode a data URI out of the markup and treat it as a remote
resource. So this writes two real files and points the metadata at them.

  share/og-card.png   1200x630, the wide card most previews show
  share/icon-512.png  square, for the ones that want an icon

Paths are RELATIVE on purpose. The live app is a different repo at a
different origin, and an absolute URL baked in here would point every
share from it back at the test deployment. Apple's own link metadata
resolves a relative og:image against the page URL, as do the other
crawlers in practice.

  python3 tools/gen-share-card.py           # write the files and the meta
  python3 tools/gen-share-card.py --check   # verify both exist and match
"""
import argparse
import importlib.util
import io
import os
import sys

from PIL import Image, ImageDraw, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHARE = os.path.join(ROOT, "share")
INDEX = os.path.join(ROOT, "index.html")

CARD_W, CARD_H = 1200, 630
ICON_PX = 512

# Straight from the app: --paper and the three theme stops the wordmark and
# the icon's own V already use. A preview card in different colours from the
# app it opens is the thing that made this worth doing at all.
BG_TOP, BG_BOTTOM = "#241C21", "#121016"
BRAND = ["#FFD37A", "#F5804D", "#C23B7A"]
INK = (244, 240, 236)
SOFT = (166, 158, 168)

TITLE = "Nova"
TAGLINE = "Study app for Class 26E"

BEGIN = "<!-- share-card: generated by tools/gen-share-card.py -->"
END = "<!-- /share-card -->"


def load_icon_module():
    """gen-app-icon.py draws the icon; this borrows it rather than redrawing."""
    path = os.path.join(ROOT, "tools", "gen-app-icon.py")
    spec = importlib.util.spec_from_file_location("gen_app_icon", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def hex_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def vertical_gradient(w, h, top, bottom):
    t, b = hex_rgb(top), hex_rgb(bottom)
    img = Image.new("RGB", (w, h))
    px = img.load()
    for y in range(h):
        f = y / max(1, h - 1)
        col = tuple(round(t[i] + (b[i] - t[i]) * f) for i in range(3))
        for x in range(w):
            px[x, y] = col
    return img


def radial_glow(w, h, cx, cy, radius, colour, strength):
    """One of the app's ambient glows, so the card reads as the same surface."""
    layer = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(layer)
    d.ellipse([cx - radius, cy - radius * 0.72, cx + radius, cy + radius * 0.72],
              fill=int(255 * strength))
    layer = layer.filter(ImageFilter.GaussianBlur(radius * 0.45))
    return Image.composite(Image.new("RGB", (w, h), hex_rgb(colour)),
                           Image.new("RGB", (w, h), (0, 0, 0)), layer), layer


def load_font(size, bold=True):
    from PIL import ImageFont
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf" if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for c in candidates:
        if os.path.exists(c):
            return ImageFont.truetype(c, size)
    return ImageFont.load_default()


def gradient_text(text, font, stops):
    """The wordmark's gold-to-magenta ramp, clipped to the glyphs.

    Mapped across the TEXT's own bounding box, not across some larger
    canvas - the same mistake the app icon's V made, where a ramp spread
    over the whole tile left the gold and the magenta off the ends of the
    shape and the glyph came out uniformly salmon.
    """
    from PIL import ImageFont
    probe = Image.new("L", (8, 8))
    box = ImageDraw.Draw(probe).textbbox((0, 0), text, font=font)
    w, h = box[2] - box[0] + 4, box[3] - box[1] + 4
    off = (-box[0] + 2, -box[1] + 2)
    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).text(off, text, font=font, fill=255)
    ramp = Image.new("RGB", (w, h))
    px = ramp.load()
    cols = [hex_rgb(c) for c in stops]
    for x in range(w):
        f = x / max(1, w - 1) * (len(cols) - 1)
        i = min(int(f), len(cols) - 2)
        t = f - i
        col = tuple(round(cols[i][k] + (cols[i + 1][k] - cols[i][k]) * t) for k in range(3))
        for y in range(h):
            px[x, y] = col
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    out.paste(ramp, (0, 0), mask)
    return out


def build_card(icon):
    card = vertical_gradient(CARD_W, CARD_H, BG_TOP, BG_BOTTOM)
    for cx, cy, r, col, strength in [
        (CARD_W * 0.18, CARD_H * 0.22, CARD_W * 0.42, BRAND[0], 0.16),
        (CARD_W * 0.86, CARD_H * 0.84, CARD_W * 0.40, BRAND[2], 0.14),
    ]:
        glow, mask = radial_glow(CARD_W, CARD_H, cx, cy, r, col, strength)
        card = Image.blend(card, Image.blend(card, glow, 0.55), 1.0) \
            if False else Image.composite(Image.blend(card, glow, 0.5), card, mask)

    tile = icon.resize((300, 300), Image.LANCZOS).convert("RGBA")
    # iOS's own corner radius, near enough, so the tile reads as an app icon
    # rather than as a photograph of a square.
    mask = Image.new("L", (300 * 4, 300 * 4), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, 300 * 4 - 1, 300 * 4 - 1],
                                           radius=int(300 * 4 * 0.2237), fill=255)
    tile.putalpha(mask.resize((300, 300), Image.LANCZOS))

    shadow = Image.new("RGBA", (CARD_W, CARD_H), (0, 0, 0, 0))
    shadow.paste((0, 0, 0, 150), (118, 178, 118 + 300, 178 + 300), tile.split()[3])
    shadow = shadow.filter(ImageFilter.GaussianBlur(22))
    card = Image.alpha_composite(card.convert("RGBA"), shadow)
    card.paste(tile, (110, 165), tile)

    title_font = load_font(112, bold=True)
    tag_font = load_font(40, bold=False)
    word = gradient_text(TITLE, title_font, BRAND)
    card.alpha_composite(word, (470, 214))
    d = ImageDraw.Draw(card)
    # Measured and wrapped rather than trusted: the second line ran off the
    # right edge of the card at this size, which is the one thing a preview
    # image cannot get away with.
    lines = [TAGLINE, "Drills, exams and a", "class leaderboard."]
    y = 372
    for i, line in enumerate(lines):
        col = SOFT if i == 0 else (120, 114, 124)
        while d.textbbox((0, 0), line, font=tag_font)[2] > CARD_W - 474 - 60 and len(line) > 4:
            line = line[:-2] + "\u2026"
        d.text((474, y), line, font=tag_font, fill=col)
        y += 54
    return card.convert("RGB")


META = """{begin}
<meta property="og:type" content="website">
<meta property="og:site_name" content="Nova">
<meta property="og:title" content="Nova - Class 26E">
<meta property="og:description" content="{tagline} Drills, exams, a daily question and a class leaderboard.">
<meta property="og:image" content="share/og-card.png">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="{w}">
<meta property="og:image:height" content="{h}">
<meta property="og:image:alt" content="The Nova app icon beside the Nova wordmark">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Nova - Class 26E">
<meta name="twitter:description" content="{tagline} Drills, exams, a daily question and a class leaderboard.">
<meta name="twitter:image" content="share/og-card.png">
<meta name="description" content="{tagline} Drills, exams, a daily question and a class leaderboard.">
<link rel="image_src" href="share/og-card.png">
{end}"""


def write_meta():
    src = io.open(INDEX, encoding="utf-8").read()
    block = META.format(begin=BEGIN, end=END, tagline=TAGLINE + ".",
                        w=CARD_W, h=CARD_H)
    if BEGIN in src and END in src:
        head = src.index(BEGIN)
        tail = src.index(END) + len(END)
        src = src[:head] + block + src[tail:]
    else:
        # Right after the title, so a crawler that stops reading early has it.
        anchor = "<meta name=\"apple-mobile-web-app-title\" content=\"Nova\">"
        assert src.count(anchor) == 1, "anchor for the share block moved"
        src = src.replace(anchor, anchor + "\n" + block, 1)
    io.open(INDEX, "w", encoding="utf-8").write(src)


def check():
    problems = []
    for name, size in [("og-card.png", (CARD_W, CARD_H)), ("icon-512.png", (ICON_PX, ICON_PX))]:
        path = os.path.join(SHARE, name)
        if not os.path.exists(path):
            problems.append("share/%s is missing" % name)
            continue
        with Image.open(path) as im:
            if im.size != size:
                problems.append("share/%s is %s, expected %s" % (name, im.size, size))
    src = io.open(INDEX, encoding="utf-8").read()
    for needed in ['property="og:image" content="share/og-card.png"',
                   'name="twitter:image" content="share/og-card.png"',
                   'property="og:title"', 'name="description"']:
        if needed not in src:
            problems.append("index.html is missing %s" % needed)
    if "http://" in src.split(END)[0].split(BEGIN)[-1] or \
       "https://" in src.split(END)[0].split(BEGIN)[-1]:
        problems.append("the share block carries an absolute URL; it must stay "
                        "relative so the live origin does not point at this one")
    for p in problems:
        print("  FAIL " + p)
    if not problems:
        print("  share/og-card.png and share/icon-512.png present, meta points at them")
    return 1 if problems else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the files exist and the meta names them")
    args = ap.parse_args()
    if args.check:
        return check()

    icon_mod = load_icon_module()
    icon = icon_mod.render("pixel", size=ICON_PX).convert("RGB")
    os.makedirs(SHARE, exist_ok=True)
    icon.save(os.path.join(SHARE, "icon-512.png"), optimize=True)
    build_card(icon).save(os.path.join(SHARE, "og-card.png"), optimize=True)
    write_meta()
    print("wrote share/og-card.png (%dx%d), share/icon-512.png (%d), and the meta block"
          % (CARD_W, CARD_H, ICON_PX))
    return 0


if __name__ == "__main__":
    sys.exit(main())
