#!/usr/bin/env python3
"""Regenerate the <link rel="apple-touch-startup-image"> block in index.html.

iOS does NOT use the manifest's background_color for a home-screen app's
launch screen. With no startup image it paints the launch screen WHITE, which
is the white flash reported on every launch, before the app's own splash gets
a chance to render. The only way to colour that screen is to hand iOS an
image for the exact device resolution, matched by media query - it ignores
anything whose dimensions do not match, and falls back to white.

Every image here is a flat SPLASH_COLOR, matching #splashscreen's own
background, so the launch screen and the splash are the same colour and the
handover between them is invisible. A solid-colour PNG is tiny (under a
kilobyte even at 1320x2868), so covering every device costs ~40KB of an
already 1.6MB file, and gzip collapses the repetition further.

REAL FILES, in launch/, not data URIs - and that change is the whole point of
this script's second version. The first shipped 42 correct link tags carrying
correct PNGs as data URIs, and the white flash did not move. It was not a
coverage gap: an iPhone 17 Pro Max is 440x956 at 3x, which the 16 Pro Max
entry already matched exactly. The links were right and the images were
right, so what was left was the delivery: iOS has to have these images
BEFORE the page it found them in has loaded, and every documented
implementation of this feature references a fetchable path. A data URI is
not one.

The cost is that index.html is no longer the whole app: launch/ has to travel
with it. See "Going live" in CLAUDE.md, where that is now stated twice.

    python3 tools/gen-startup-images.py          # write launch/ and index.html
    python3 tools/gen-startup-images.py --check   # verify; exit 1 if stale or
                                                  # if any launch/ file is gone
"""
import argparse
import base64
import io
import os
import re
import sys

from PIL import Image

SPLASH_COLOR = (0x0A, 0x0A, 0x0A)
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
INDEX = os.path.join(ROOT, "index.html")
LAUNCH_REL = "launch"
LAUNCH_DIR = os.path.join(ROOT, LAUNCH_REL)
BEGIN = "<!-- BEGIN apple-touch-startup-image (generated by tools/gen-startup-images.py) -->"
END = "<!-- END apple-touch-startup-image -->"

# (css width, css height, device pixel ratio, what it covers)
DEVICES = [
    (320, 568, 2, "iPhone SE (1st gen), 5s"),
    (375, 667, 2, "iPhone 6/7/8, SE (2nd/3rd gen)"),
    (414, 736, 3, "iPhone 6/7/8 Plus"),
    (375, 812, 3, "iPhone X/XS, 11 Pro, 12/13 mini"),
    (414, 896, 2, "iPhone XR, 11"),
    (414, 896, 3, "iPhone XS Max, 11 Pro Max"),
    (390, 844, 3, "iPhone 12/12 Pro, 13/13 Pro, 14"),
    (428, 926, 3, "iPhone 12/13 Pro Max, 14 Plus"),
    (393, 852, 3, "iPhone 14 Pro, 15/15 Pro, 16, 17"),
    (430, 932, 3, "iPhone 14 Pro Max, 15 Plus/Pro Max, 16 Plus"),
    (402, 874, 3, "iPhone 16 Pro, 17 Pro"),
    (440, 956, 3, "iPhone 16 Pro Max, 17 Pro Max"),
    (744, 1133, 2, "iPad mini (6th gen and later)"),
    (768, 1024, 2, "iPad mini (up to 5th gen), iPad 9.7\""),
    (810, 1080, 2, "iPad 10.2\""),
    (820, 1180, 2, "iPad Air 10.9\", iPad (10th gen)"),
    (834, 1112, 2, "iPad Pro 10.5\""),
    (834, 1194, 2, "iPad Pro 11\""),
    (834, 1210, 2, "iPad Air/Pro 11\" (M4)"),
    (1024, 1366, 2, "iPad Pro 12.9\""),
    (1032, 1376, 2, "iPad Pro 13\" (M4)"),
]


def png_data_uri(px_w, px_h):
    """A flat SPLASH_COLOR PNG, as small as PNG can express it."""
    im = Image.new("P", (px_w, px_h), 0)
    im.putpalette(list(SPLASH_COLOR) + [0] * (256 * 3 - 3))
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True, compress_level=9, bits=1)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def write_png(px_w, px_h):
    """Write launch/<w>x<h>.png if it is not already there. Returns the path."""
    name = "{}x{}.png".format(px_w, px_h)
    path = os.path.join(LAUNCH_DIR, name)
    if not os.path.exists(path):
        im = Image.new("P", (px_w, px_h), 0)
        im.putpalette(list(SPLASH_COLOR) + [0] * (256 * 3 - 3))
        im.save(path, "PNG", optimize=True, compress_level=9, bits=1)
    return LAUNCH_REL + "/" + name


def build_block(write=True):
    lines = [BEGIN,
             "<!-- Flat #%02X%02X%02X, the same colour as #splashscreen, so the launch" % SPLASH_COLOR,
             "     screen and the app's own splash are indistinguishable. Regenerate with",
             "     tools/gen-startup-images.py rather than editing by hand; iOS ignores any",
             "     image whose size does not match the device exactly and paints white",
             "     instead, which is the whole bug this exists to fix.",
             "     The files live in launch/ and MUST be deployed alongside index.html. -->"]
    wanted = []
    if write:
        os.makedirs(LAUNCH_DIR, exist_ok=True)
    for w, h, dpr, label in DEVICES:
        for orient, (pw, ph) in (("portrait", (w * dpr, h * dpr)),
                                 ("landscape", (h * dpr, w * dpr))):
            href = write_png(pw, ph) if write else "{}/{}x{}.png".format(LAUNCH_REL, pw, ph)
            wanted.append(href)
            lines.append(
                '<link rel="apple-touch-startup-image" '
                'media="screen and (device-width: {w}px) and (device-height: {h}px) '
                'and (-webkit-device-pixel-ratio: {d}) and (orientation: {o})" '
                'href="{u}"><!-- {lab} -->'.format(w=w, h=h, d=dpr, o=orient, u=href, lab=label))
    # Catch-all, last and with NO media attribute. iOS matches on exact
    # device dimensions and falls back to WHITE on any mismatch, so a device
    # this list does not name - a phone released after it was written, most
    # obviously - would get the flash back with nothing to explain why. A
    # media-less entry is the only thing that can cover a size not known in
    # advance; every specific entry above still wins where it matches.
    href = write_png(1320, 2868) if write else "{}/1320x2868.png".format(LAUNCH_REL)
    wanted.append(href)
    lines.append('<link rel="apple-touch-startup-image" href="{u}">'
                 '<!-- catch-all for any device not listed above -->'.format(u=href))
    lines.append(END)
    return "\n".join(lines), wanted


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify; exit 1 if index.html is stale or a launch/ file is missing")
    args = ap.parse_args()

    if args.check:
        block, wanted = build_block(write=False)
        src = io.open(INDEX, encoding="utf-8").read()
        if BEGIN not in src:
            print("STALE: no generated block in index.html")
            sys.exit(1)
        current = src[src.index(BEGIN):src.index(END) + len(END)]
        if current != block:
            print("STALE: the generated block does not match this script's output")
            sys.exit(1)
        missing = [h for h in dict.fromkeys(wanted)
                   if not os.path.exists(os.path.join(ROOT, h))]
        if missing:
            print("MISSING: %d launch image(s) the page references are not on disk:" % len(missing))
            for m in missing[:6]:
                print("   " + m)
            print("Without them iOS falls back to a WHITE launch screen, silently.")
            sys.exit(1)
        print("up to date (%d devices, %d link tags, %d files in %s/)"
              % (len(DEVICES), len(DEVICES) * 2 + 1, len(set(wanted)), LAUNCH_REL))
        return

    block, wanted = build_block(write=True)
    src = io.open(INDEX, encoding="utf-8").read()
    if BEGIN in src:
        start = src.index(BEGIN)
        stop = src.index(END) + len(END)
        src = src[:start] + block + src[stop:]
    else:
        anchor = '<link rel="manifest"'
        src = src.replace(anchor, block + "\n" + anchor, 1)
    io.open(INDEX, "w", encoding="utf-8").write(src)

    # Sweep launch/ of anything no longer referenced, so the folder cannot
    # silently accumulate images for devices that were removed.
    keep = {os.path.basename(h) for h in wanted}
    for name in sorted(os.listdir(LAUNCH_DIR)):
        if name.endswith(".png") and name not in keep:
            os.remove(os.path.join(LAUNCH_DIR, name))
            print("removed stale " + LAUNCH_REL + "/" + name)

    size = sum(os.path.getsize(os.path.join(LAUNCH_DIR, f)) for f in os.listdir(LAUNCH_DIR))
    print("wrote %d link tags for %d devices, %d files in %s/ (%.0f KB total)"
          % (len(DEVICES) * 2 + 1, len(DEVICES), len(set(wanted)), LAUNCH_REL, size / 1024.0))


if __name__ == "__main__":
    main()
